name: Java Formatter

on:
  push:
    branches:
      - BottomNavigation
  pull_request:
    branches:
      - BottomNavigation

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
